#ifndef REDMAGIC_CONFIG_H_
#define REDMAGIC_CONFIG_H_

// used for debugging
//#define CONF_COMPILE_IN_PARENT

#define CONF_NUMBER_OF_JUMPS_BEFORE_TRACE 10

#define CONF_VERBOSE

#define CONF_GLOBAL_ABORT

#endif // REDMAGIC_CONFIG_H_
